### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by Unknow0059** [daveleroy/SublimeDebugger#260]
annoying bugs.

after installing i get a TypeError, restarting makes the error go away.

after installing the python adapter and adding the configuration I got a "Debugging ended unexpectedly" error when trying to use the debugger.

after uninstalling the plugin, my sublime text changed its theme to Mariana, for some reason. Twice. Once for every time I reinstalled the plugin.

In the second time with the plugin installed, it gave a 403 error when fetching the adapters, all of them.

it's unusable.

**Comment by daveleroy** [comment]
Use `Debugger: Show Protocol` and add the log and include the debug configuration you are using

Include the actual messages you get instead of just saying you got an error I got a TypeError that is completely useless.

`In the second time with the plugin installed, it gave a 403 error when fetching the adapters, all of them.` you keep uninstalling it and trying to install adapters so github has rate limited you. If you looked up 403 in the search you would see this https://github.com/daveleroy/SublimeDebugger/issues/241

`after uninstalling the plugin, my sublime text changed its theme to Mariana, for some reason. Twice. Once for every time I reinstalled the plugin.` seems unlikely to be a problem with this package it doesn't touch your settings.
